---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
production: # work model
  :concurrency: 5
:queues:
  - [mailers, 5]
  - [update_assignment]
  - [update_project]
  - [pfop_video_images]
  - [start_assign, 10]
  - [inc_good_stock, 5]